### ISSUE TITLE
Symbol’s function definition is void: json-serialize

### ISSUE THREAD

**Issue by stew** [zerolfx/copilot.el#6] opened 2022-04-01 20:13 UTC
I this error when I try to run `copilot-login`

```
Symbol’s function definition is void: json-serialize
```
M-x version says:
```
GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.5, cairo version 1.16.0) of 2021-04-04, unofficial emacs-snapshot build: http://emacs.ganneff.de/, git commit dd5ba88afbb63f54603cc632fc55993c04531a85
```

**Comment by zerolfx** [comment] 2022-04-01 20:38
Your Emacs was built without JSON support. I guess using an official Emacs can solve this problem.

There is a similar problem: https://github.com/org-roam/org-roam-ui/issues/63#issuecomment-899105994

**Comment by zerolfx** [comment] 2022-04-12 04:32
I close the issue since it is not a bug and the thread is not active.

**Closed by zerolfx** 2022-04-12 04:32 UTC
