### ISSUE TITLE
copilot-login jsonrpc error

### ISSUE THREAD

**Issue by genworks** [zerolfx/copilot.el#34] opened 2022-06-28 20:42 UTC
Hi,
 
  I have this working on Mac Montery with emacs 28.1 and nvm node 17.9.1. 
 
  But trying what I think is identical setup on WSL2, I get the following upon `M-x copilot-login`:

```
jsonrpc-request: jsonrpc-error: "request id=4 failed:", (jsonrpc-error-code . -32602), (jsonrpc-error-\
message . "Invalid params:  must be object"), (jsonrpc-error-data)

``` 

`copilot-node-executable` is set to `"node"` and in a shell within emacs, `node --version`  returns `v17.9.1` (same node version as on my Mac where copilot.el works)

Contents of `*copilot-events*` : 

```
(:jsonrpc "2.0" :id 2 :method "setEditorInfo" :params
          (:editorInfo
           (:name "Emacs" :version "26.3")
           :editorPluginInfo
           (:name "copilot.el" :version "0.9.6")))
[client-request] (id:3) Tue Jun 28 16:28:58 2022:
(:jsonrpc "2.0" :id 3 :method "signInInitiate" :params 'nil)
[server-reply] (id:2) Tue Jun 28 16:28:58 2022:
(:jsonrpc "2.0" :id 2 :result "OK")
[server-reply] (id:3) ERROR Tue Jun 28 16:28:58 2022:
(:jsonrpc "2.0" :id 3 :error
          (:code -32602 :message "Invalid params:  must be object"))
[client-request] (id:4) Tue Jun 28 16:35:17 2022:
(:jsonrpc "2.0" :id 4 :method "signInInitiate" :params 'nil)
[server-reply] (id:4) ERROR Tue Jun 28 16:35:17 2022:
(:jsonrpc "2.0" :id 4 :error
          (:code -32602 :message "Invalid params:  must be object"))

```

Contents of `*copilot-stderr*` does not exist. 

I don't think an exception is being thrown, it's just an rpc error presumably between the node executable in my WSL2 and the remote copilot authentication server? 

Thanks,

Dave

**Comment by zerolfx** [comment] 2022-06-28 20:58
Please try again with Emacs 27+. I guess the built-in `jsonrpc` package is slightly different in Emacs 26.

**Comment by zerolfx** [comment] 2022-06-28 21:09
duplicate of #23

**Closed by zerolfx** 2022-06-28 21:09 UTC

**Comment by genworks** [comment] 2022-06-28 22:35
Thanks, indeed it was the Emacs version, I upgraded to Emacs 28.1 and it works.
